version: '3'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings_docker
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    restart: always
    networks:
      - ecom_network

networks:
  ecom_network:
    driver: bridge